### PR TITLE
feat: Add support for automatically adding custom tools to profiles

### PR DESCRIPTION
**Pull request by Log1x**
This adds support for adding tools to profiles as bubble, suggestion, or toolbar by default.

```php
$this
    ->icon('heroicon-o-cube-transparent')
    ->label('Notice')
    ->type(ToolType::Block)
    ->renderedView(view: 'scribble-tools.notice')
    ->optionsModal(NoticeModal::class)
    ->suggestionTool()
    ->toolbarTool()
    ->bubbleTool();
```

Alternatively, I can change this to only affect [`DefaultProfile`](https://github.com/awcodes/scribble/blob/main/src/Profiles/DefaultProfile.php) instead if needed (kinda leaning towards it, would also be less code).

This paired with #37 should hopefully improve DX when getting started making changes/generated tools take effect immediately.

From personal experience, I sort of feel like `->suggestionTool()` should be default in the tool generation stub(s).

Another thing to consider would be maybe dropping the `Tool` suffix on the methods.

### CODE REVIEW

**Comment by awcodes** [comment]
How much trouble would it be to have it default to the `DefaultProfile` but allow passing an array of profiles for it to be added to?

**Comment by Log1x** [comment]
Shouldn't be an issue. Will push an update soon!

**Comment by awcodes** [comment]
Sorry. I pushed some changes that are going to conflict with this. My fault. Should have waited on you.

**Comment by Log1x** [comment]
> Sorry. I pushed some changes that are going to conflict with this. My fault. Should have waited on you.

No problem. I'm almost done with the implementation and I'll fix the conflicts.

**Comment by Log1x** [comment]
everything is done and should be working. could alternatively use `Arr::wrap()` on the getters and allow the profiles to be a string on the property instead of my `is_string` check in the setters. Let me know if you want that changed at all.

**Comment by awcodes** [comment]
Awesome. I appreciate it.

**Comment by awcodes** [comment]
I do think Arr:wrap() would be cleaner.

**Comment by Log1x** [comment]
> I do think Arr:wrap() would be cleaner.

agreed. will push the change momentarily.

**Comment by Log1x** [comment]
done

**Comment by awcodes** [comment]
Thank you for your work on this. It will be in the next release. 

I didn't want you to have to do it again because I keep creating conflicts for you. LOL.

I have tagged this in the PR to make sure you still get credit.

**Pull request closed without merging**
